### ISSUE TITLE
Midnight Club 3 DUB Edition: pgraph_surface_invalidate: assertion "surface != d->pgraph.zeta_binding"

### ISSUE THREAD

**Issue by Fabxx** [xemu-project/xemu#349]
### Title Information

* Titles: Midnight Club 3: DUB Edition TT-121 [54540079]
* https://xemu.app/titles/54540079/#Midnight-Club-3-DUB-Edition

### Bug Description

Game crashes while pressing start on main menu

Steps to reproduce this issue:
1. (1. Launch the game and reach the menu, press start and it will crash.)

### Expected Behavior

Should be able to continue without the assertion

### Version

0.6.6

### System Information

CPU:          Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
OS Platform:  Linux
OS Version:   Manjaro Linux
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce GTX 970/PCIe/SSE2
Driver:       4.0.0 NVIDIA 510.68.02
Shader:       4.00 NVIDIA via Cg compiler

**Comment by Fabxx** [comment]
GDB backtrace for the bug:
```xemu: ../hw/xbox/nv2a/pgraph.c:5231: pgraph_surface_invalidate: asserzione "surface != d->pgraph.zeta_binding" non riuscita.

Thread 10 "xemu" received signal SIGABRT, Aborted.
0x00007ffff677534c in __pthread_kill_implementation () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff677534c in __pthread_kill_implementation () at /usr/lib/libc.so.6
#1  0x00007ffff67284b8 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff6712534 in abort () at /usr/lib/libc.so.6
#3  0x00007ffff671245c in _nl_load_domain.cold () at /usr/lib/libc.so.6
#4  0x00007ffff6721116 in  () at /usr/lib/libc.so.6
#5  0x0000555555a46199 in pgraph_surface_invalidate (d=0x7fff7a8ce010, surface=0x7fff3a840350)
    at ../hw/xbox/nv2a/pgraph.c:5231
#6  0x0000555555a4741b in pgraph_surface_put (surface_in=0x7fff7a215410, addr=<optimized out>, d=0x7fff7a8ce010)
    at ../hw/xbox/nv2a/pgraph.c:5173
#7  pgraph_update_surface_part (d=0x7fff7a8ce010, upload=<optimized out>, color=<optimized out>)
    at ../hw/xbox/nv2a/pgraph.c:5855
#8  0x0000555555a47cae in pgraph_update_surface
    (d=0x7fff7a8ce010, upload=<optimized out>, color_write=<optimized out>, zeta_write=<optimized out>)
    at ../hw/xbox/nv2a/pgraph.c:5951
#9  0x0000555555a47f51 in pgraph_NV097_SET_BEGIN_END_handler
    (d=0x7fff7a8ce010, pg=0x7fff7a8f0cc8, subchannel=<optimized out>, method=<optimized out>, parameter=6, parameters=<optimized out>, num_words_available=1, num_words_consumed=0x7fff7a215808, inc=true) at ../hw/xbox/nv2a/pgraph.c:2795
#10 0x0000555555a3b1a4 in pgraph_method(NV2AState*, unsigned int, unsigned int, uint32_t, uint32_t*, size_t, size_t, _Bool)
    (d=0x7fff7a8ce010, subchannel=0, method=6140, parameter=6, parameters=0x7fff8f9eb9fc, num_words_available=1, max_lookahead_words=283601, inc=true) at ../hw/xbox/nv2a/pgraph.c:1118
#11 0x0000555555a3cf74 in pfifo_run_puller
    (max_lookahead_words=<optimized out>, num_words_available=1, parameters=0x7fff8f9eb9fc, parameter=6, method_entry=6140, d=0x5c0000006e) at ../hw/xbox/nv2a/pfifo.c:225
#12 pfifo_run_pusher (d=0x5c0000006e) at ../hw/xbox/nv2a/pfifo.c:337
#13 pfifo_thread(void*) (arg=arg@entry=0x7fff7a8ce010) at ../hw/xbox/nv2a/pfifo.c:489
--Type <RET> for more, q to quit, c to continue without paging--c
#14 0x0000555555bf53e9 in qemu_thread_start(void*) (args=0x7fff7a2159d0) at ../util/qemu-thread-posix.c:541
#15 0x00007ffff67735c2 in start_thread () at /usr/lib/libc.so.6
#16 0x00007ffff67f8584 in clone () at /usr/lib/libc.so.6
```

**Comment by abaire** [comment]
This is due to the same underlying cause as #405 and the fix there also allowed me to get into a race.
