### ISSUE TITLE
Operation Flashpoint: Segfault on Windows/NVIDIA

### ISSUE THREAD

**Issue by simi** [xemu-project/xemu#406]
### Title Information

* https://xemu.app/titles/434d005a/#Operation-Flashpoint-Elite

### Bug Description
Steps to reproduce this issue:

1. Start game in Windows/NVIDIA GPU combination
2. It crashes after splash screens.

Using same ISO I was able to get to the menu (and overall play the game without problems) using Linux/INTEL GPU. To get the game running on Windows/NVIDIA it is possible to modify the iso and "nullify" game videos (just replace them with empty files). Those videos are playing in the menu (right before the crash) and it is most likely related to this problem.

### Expected Behavior
Videos are played without problem. Main menu works and you can reach the game.

### Version
https://github.com/mborgerson/xemu/releases/tag/build-202107110629

### Additional Context
There is nothing noted in logs. I tried to run debug release on Windows with GDB to see anything related. I'm attaching backtrace on segfault.

```
Thread 26 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 13116.0x22dc]
0x000000006c0e31e0 in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
(gdb) bt
#0  0x000000006c0e31e0 in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#1  0x000000006c0e2e50 in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#2  0x000000006bffd0a9 in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#3  0x000000006bffc5db in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#4  0x000000006bffc95f in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#5  0x000000006c014eb8 in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#6  0x000000006c0155fd in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#7  0x000000006c0b8a4e in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#8  0x000000006c0b8d8f in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#9  0x000000006bbfd4f3 in ?? () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#10 0x000000006bd04421 in ?? () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#11 0x000000006bd085f0 in ?? () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#12 0x000000006bd093b1 in ?? () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#13 0x000000006bd142b8 in ?? () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#14 0x000000006bbac035 in ?? () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#15 0x000000006bd28e70 in ?? () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#16 0x000000006bd28c20 in ?? () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#17 0x000000006bf9c8db in nvoglv64!DrvValidateVersion () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#18 0x00007fffe99a7034 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#19 0x00007fffea602651 in ntdll!RtlUserThreadStart () from C:\WINDOWS\SYSTEM32\ntdll.dll
#20 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

I have checked all threads using `threads apply all bt`, but nothing related is present in there - no reference to any line in xemu itself.

**Comment by Triticum0** [comment]
This also affected me on window when i tested in with my 5700xt so it affect both manufactures

**Comment by Triticum0** [comment]
@simi Retest on windows with #539 It should be fixed

**Comment by simi** [comment]
@Triticum0 I can confirm video playback works now and game doesn't crash. But playback speed is really slow (like 0.5 FPS). I'll check the performance on better system. But I was able to run this without problems on Linux on integrated GPU.

**Comment by simi** [comment]
@mborgerson since I'm still banned on discord, there is no way for me to change https://xemu.app/titles/434d005a/#Operation-Flashpoint-Elite entry. Can you please change it?
