### ISSUE TITLE
Dreamfall - The Longest Journey: Crash after chaper 6

### ISSUE THREAD

**Issue by IguanaMeow** [xemu-project/xemu#888]
### Title

https://xemu.app/titles/41590004/#Dreamfall-The-Longest-Journey

NTSC USA

### Bug Description

Game crashes when finishing "Chapter 6: Morpheus" right after this interactive dialogue scene:
![Screen_2022-05-06_20-32](https://user-images.githubusercontent.com/6662831/167197880-a9ccc0bd-764a-4f71-a020-ebbfb9889aeb.png)
![Screen_2022-05-06_20-29](https://user-images.githubusercontent.com/6662831/167197891-7e07c074-8639-4482-acbe-833cbd155a6a.png)

### Expected Behavior

After the loading screen "Chapter 7: Destiny" should start playing the cutscene as so:
![11](https://user-images.githubusercontent.com/6662831/167199966-71b39249-e9b3-4a36-813c-3f96a239945e.png)
![22](https://user-images.githubusercontent.com/6662831/167199976-3fd1b869-6b3e-4f20-86b0-66eea84e7fc0.png)

### xemu Version

0.6.6

### System Information

OS: Devuan Ceres/Unstable GNU/Linux
CPU: AMD Ryzen 5 2600
GPU: AMD Radeon RX 570 8GB
GPU Driver: Mesa 22.0.2

### Additional Context

Terminal output:

xemu_version: 0.6.6
xemu_branch: master
xemu_commit: c2e0067538fa5d24e57effce1adca172db6e8117
xemu_date: Tue May  3 09:41:49 PM UTC 2022
xemu_settings_get_path: config path: /home/iguana/.local/share/xemu/xemu/xemu.toml
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option glsl_zero_init overridden by environment.
ATTENTION: default value of option force_integer_tex_nearest overridden by environment.
CPU: AMD Ryzen 5 2600 Six-Core Processor            
OS_Version: Devuan GNU/Linux 5 (daedalus/ceres)
GL_VENDOR: AMD
GL_RENDERER: AMD Radeon RX 570 Series (polaris10, LLVM 14.0.1, DRM 3.44, 5.17.5-xanmod1)
GL_VERSION: 4.6 (Core Profile) Mesa 22.0.2
GL_SHADING_LANGUAGE_VERSION: 4.60
Created QEMU launch parameters: xemu -machine xbox,bootrom=/home/iguana/.local/share/xemu/xemu/mcpx_1.0.bin,short-animation=on,kernel-irqchip=off -device smbus-storage,file=/home/iguana/.local/share/xemu/xemu/eeprom.bin -bios /home/iguana/.local/share/xemu/xemu/Complex_4627v1.03.bin -m 128 -drive index=0,media=disk,file=/home/iguana/.local/share/xemu/xemu/xbox_hdd.qcow2,locked=on -drive index=1,media=cdrom,file=/home/iguana/Games/xbox/Dreamfall - The Longest Journey (USA).iso -display xemu 
double free or corruption (!prev)
Aborted

**Comment by IguanaMeow** [comment]
So, I have re-compiled with the --debug flag and here is the output of the crash when ran with GDB:
```
gdb xemu
GNU gdb (Debian 11.2-1) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from xemu...
(gdb) r
Starting program: /home/iguana/.local/bin/xemu 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4c62640 (LWP 5777)]
xemu_version: 
xemu_branch: master
xemu_commit: 306891b98cd77927060dd2208e9f274e646c9241
xemu_date: Fri May  6 07:08:19 PM UTC 2022
xemu_settings_get_path: config path: /home/iguana/.local/share/xemu/xemu/xemu.toml
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option glsl_zero_init overridden by environment.
ATTENTION: default value of option force_integer_tex_nearest overridden by environment.
[New Thread 0x7fffe4138640 (LWP 5779)]
[New Thread 0x7fffe37f6640 (LWP 5780)]
[New Thread 0x7fffe2ff5640 (LWP 5781)]
[New Thread 0x7fffe27f4640 (LWP 5782)]
[New Thread 0x7fffe1ff3640 (LWP 5783)]
[New Thread 0x7fffe17f2640 (LWP 5784)]
[New Thread 0x7fffe0ff1640 (LWP 5785)]
[New Thread 0x7fffc3fff640 (LWP 5786)]
[New Thread 0x7fffc37fe640 (LWP 5787)]
[New Thread 0x7fffc2ffd640 (LWP 5788)]
[New Thread 0x7fffc27fc640 (LWP 5789)]
[New Thread 0x7fffc1ffb640 (LWP 5790)]
[New Thread 0x7fffc17fa640 (LWP 5791)]
[New Thread 0x7fffc0ff9640 (LWP 5792)]
[New Thread 0x7fffa3fff640 (LWP 5793)]
[New Thread 0x7fffa37fe640 (LWP 5794)]
[New Thread 0x7fffa2ffd640 (LWP 5796)]
[Thread 0x7fffa2ffd640 (LWP 5796) exited]
[Thread 0x7fffa37fe640 (LWP 5794) exited]
[New Thread 0x7fffa37fe640 (LWP 5797)]
[New Thread 0x7fffa2ffd640 (LWP 5798)]
CPU: AMD Ryzen 5 2600 Six-Core Processor            
OS_Version: Devuan GNU/Linux 5 (daedalus/ceres)
GL_VENDOR: AMD
GL_RENDERER: AMD Radeon RX 570 Series (polaris10, LLVM 14.0.1, DRM 3.44, 5.17.5-xanmod1)
GL_VERSION: 4.6 (Core Profile) Mesa 22.0.2
GL_SHADING_LANGUAGE_VERSION: 4.60
[New Thread 0x7fffa27fc640 (LWP 5799)]
[New Thread 0x7fffa1ffb640 (LWP 5800)]
[New Thread 0x7fffa17fa640 (LWP 5801)]
[New Thread 0x7fffa0ff9640 (LWP 5802)]
[New Thread 0x7fff83fff640 (LWP 5803)]
Created QEMU launch parameters: /home/iguana/.local/bin/xemu -machine xbox,bootrom=/home/iguana/.local/share/xemu/xemu/mcpx_1.0.bin,short-animation=on,kernel-irqchip=off -device smbus-storage,file=/home/iguana/.local/share/xemu/xemu/eeprom.bin -bios /home/iguana/.local/share/xemu/xemu/Complex_4627v1.03.bin -m 128 -drive index=0,media=disk,file=/home/iguana/.local/share/xemu/xemu/xbox_hdd.qcow2,locked=on -drive index=1,media=cdrom,file=/home/iguana/Games/xbox/Dreamfall - The Longest Journey (USA).iso -display xemu 
[New Thread 0x7fff837fe640 (LWP 5804)]
[New Thread 0x7fff80ffb640 (LWP 5805)]
[New Thread 0x7fffe00ef640 (LWP 5806)]
[New Thread 0x7ffed3bff640 (LWP 5807)]
[New Thread 0x7ffed33fe640 (LWP 5808)]
[New Thread 0x7ffed2bfd640 (LWP 5809)]
[New Thread 0x7ffe9ffff640 (LWP 5812)]
[New Thread 0x7ffe953dc640 (LWP 5820)]
[New Thread 0x7ffe94bdb640 (LWP 5821)]
[Thread 0x7fff837fe640 (LWP 5804) exited]
[Thread 0x7ffe94bdb640 (LWP 5821) exited]
double free or corruption (!prev)

Thread 10 "xemu:sh5" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffc3fff640 (LWP 5786)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff6629546 in __GI_abort () at abort.c:79
#2  0x00007ffff6680eb8 in __libc_message
    (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff679ea78 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff668891a in malloc_printerr
    (str=str@entry=0x7ffff67a0fa0 "double free or corruption (!prev)") at malloc.c:5628
#4  0x00007ffff668a1ac in _int_free
    (av=0x7fffbc000020, p=0x7fffbc0cdc80, have_lock=<optimized out>) at malloc.c:4550
#5  0x00007ffff668d9b4 in __GI___libc_free (mem=<optimized out>) at malloc.c:3309
#6  0x00007fffeec2e4ae in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#7  0x00007fffeeb81393 in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#8  0x00007fffeeb81e63 in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#9  0x00007fffeeb7cf01 in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#10 0x00007fffeeba390d in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#11 0x00007fffee3e9549 in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#12 0x00007fffee3e90d7 in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#13 0x00007ffff67e9d80 in start_thread (arg=0x7fffc3fff640) at pthread_create.c:481
#14 0x00007ffff670176f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by Triticum0** [comment]
Could you put a save file in the issue, so any of the devs could try to reproduce the issue?

**Comment by IguanaMeow** [comment]
Walk straight ahead into the main building, skip through the dialogue, and meet the crash point at the end.
Here is the save:
[dreamfall-save.zip](https://github.com/mborgerson/xemu/files/8646091/dreamfall-save.zip)

**Comment by Triticum0** [comment]
@IguanaMeow The Issue Should be fixed If you want retest

**Comment by IguanaMeow** [comment]
Yes its fixed now, I can continue on to the next chapter :)
![xemu-2022-06-26-17-40-34](https://user-images.githubusercontent.com/6662831/175822167-6a684e01-c1bc-490f-95ab-531c81c48de5.png)
